version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: lms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: lms_db
    ports:
      - "5433:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: lms-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
